### ISSUE TITLE
Select function no i

### ISSUE THREAD

**Issue by mschauer** [tisztamo/FunctionWranglers.jl#1]
It would be nice to have a “s-“ version to select function i from a wrangler and run it
with given arguments (same for all i)

**Comment by tisztamo** [comment]
It seems also possible to add full indexing support, like `w[i](args...)` . Would that help you?

**Comment by tisztamo** [comment]
Now I see your sample: https://discourse.julialang.org/t/event-handler/59937/4

Indexing with a variable cannot be type-stable, but a new s- function may be able to speed up your code, if the wrangler is not very long (or the frequently called fns are at the beginning). To execute the i-th function, the wrangler must be iterated from 1 to i.

**Comment by mschauer** [comment]
Yes, I have a second step where a wrangler is very natural so perhaps nice to use it also for the switch type statement.

**Comment by tisztamo** [comment]
I have added `sindex`, please check the master branch to see if it helps you!

**Comment by mschauer** [comment]
This works for me.

**Comment by tisztamo** [comment]
Great! v0.1.3 is released.
